server.port: 8080

solon.app:
  name: 'xxl-mq'
  group: 'xxlmq'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO

xxl-mq:
  address: 'http://127.0.0.1:8080/xxl-mq'