server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=true"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.jingnuo.transcoding.entity
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# xxl-mq配置
xxl-mq:
  enable: false
  token: ${XXL_MQ_TOKEN:}
  address: ${XXL_MQ_ADDRESS:http://127.0.0.1:8080/xxl-mq-admin}

#转码配置
ffmpeg:
  path: ${FFMPEG_PATH:/usr/local/bin/ffmpeg}
  outputDir: ${FFMPEG_OUTPUT_DIR:/data/output}
  tmpDir: ${FFMPEG_TMP_DIR:/tmp}

#minio配置
minio:
  minio_url: ${MINIO_URL:http://127.0.0.1:9000}
  minio_name: ${MINIO_USERNAME:admin}
  minio_pass: ${MINIO_PASSWORD:}
  bucketName: ${MINIO_BUCKET:file}

#OpenOffice 安装目录
officeUrl: ${OFFICE_HOME:/opt/openoffice}


#Sa-Token 配置 (文档: https://sa-token.cc)
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk