server:
  port: 9090
  http:
    gzip:
      enable: true
  request:
    useTempfile: true
solon.config.load:
  - "app.yml"
  - "mqtt.yml"
  -
solon.app:
  name: 'sk-admin'
  group: 'admin'
#脱敏
solon.vault:
  password: "V4M6XqKvRzL9JwNd"
solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
